!Command
command:
- mconfig
positional:
- !Positional
  description: ''
  position: 0
  name: command
  optional: false
- !Positional
  description: ''
  position: 1
  name: command_parameters
  optional: true
named:
- !Flag
  description: "Read the specified config file in addition to\nthe standard ones.\
    \ Settings in this file override ones\nin the other files."
  synonyms:
  - -c
  - --config
  args: !SimpleFlagArg
    name: filepath
  optional: true
- !Flag
  description: Use this target when executing 'command'
  synonyms:
  - -t
  - --target
  args: !ChoiceFlagArg
    choices: !!set
      web:
      application:
      any:
  optional: true
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag: !Flag
  description: Display version information
  synonyms:
  - -v
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage: mconfig [options] command [command_parameters]\nOptions:\n\n  -?,-h,--help\
  \                      Display this usage information\n  -v,--version          \
  \            Display version information\n  -c,--config=<filepath>            Read\
  \ the specified config file in addition to\n                                   \
  \ the standard ones. Settings in this file override ones\n                     \
  \               in the other files.\n  -t,--target={any,web,application} Use this\
  \ target when executing 'command'\n\nTo see the list of commands, features and default\
  \ config file templates, run mconfig\nwithout any parameters\n"
generated_using:
- --help
