!Command
command:
- iu-gen-configs
positional: []
named:
- !Flag
  description: Prefix for Read 1 to be put in every config file.
  synonyms:
  - --r1-prefix
  args: !SimpleFlagArg
    name: REGEXP
  optional: true
- !Flag
  description: Prefix for Read 2.
  synonyms:
  - --r2-prefix
  args: !SimpleFlagArg
    name: REGEXP
  optional: true
- !Flag
  description: E-mail address (currently is not used for anything)
  synonyms:
  - --e-mail
  args: !SimpleFlagArg
    name: E-MAIL
  optional: true
- !Flag
  description: "Directory for output storage. INI files will also be\ngenerated in\
    \ this directory.\n"
  synonyms:
  - -o
  - --output-dir
  args: !SimpleFlagArg
    name: DIRECTORY
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: iu-gen-configs [-h] [--r1-prefix REGEXP] [--r2-prefix REGEXP]\n\
  \                      [--e-mail E-MAIL] [-o DIRECTORY]\n                      FILE\n\
  \nGenerate config files for demultiplexed FASTQ files\n\npositional arguments:\n\
  \  FILE                  TAB-delimited file to describe where samples are. The\n\
  \                        header line should be \"sample\", \"r1\", and \"r2\". Each\n\
  \                        row should list the sample name in the first column,\n\
  \                        and full path for r1 and r2. This output is\n         \
  \               automatically generated by the iu-demultiplex script.\n\noptional\
  \ arguments:\n  -h, --help            show this help message and exit\n  --r1-prefix\
  \ REGEXP    Prefix for Read 1 to be put in every config file.\n  --r2-prefix REGEXP\
  \    Prefix for Read 2.\n  --e-mail E-MAIL       E-mail address (currently is not\
  \ used for anything)\n  -o DIRECTORY, --output-dir DIRECTORY\n                 \
  \       Directory for output storage. INI files will also be\n                 \
  \       generated in this directory.\n"
generated_using:
- --help
