!Command
command:
- requantAlignedValues.py
positional: []
named:
- !Flag
  description: "OUTPUT [--file_format FILE_FORMAT]\n[--out_matrix MATRIX_OUTFILE]\n\
    [--matrix_output_method MATRIX_OUTPUT_METHOD]\n[--border_option median] [--dry_run]\
    \ [--test]\n[--cache_in_memory] [--method METHOD]\n[--realign_runs REALIGN_METHOD]\n\
    [--verbosity VERBOSITY] [--do_single_run]\n[--disable_isotopic_grouping]\n[--disable_isotopic_transfer]"
  synonyms:
  - --peakgroups_infile
  - --out
  args: !SimpleFlagArg
    name: PEAKGROUPS_INFILE
  optional: true
- !Flag
  description: "Disable grouping of isotopic variants by\npeptide_group_label, thus\
    \ disabling matching of\nisotopic variants of the same peptide across channels.\n\
    If turned off, each isotopic channel will be matched\nindependently of the other.\
    \ If enabled, the more\ncertain identification will be used to infer the\nlocation\
    \ of the peak in the other channel."
  synonyms:
  - --disable_isotopic_grouping
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "Disable the transfer of isotopic boundaries in all\ncases. If enabled\
    \ (default), the best (best score)\nisotopic channel dictates the peak boundaries\
    \ and all\nother channels use those boundaries. This ensures\nconsistency in peak\
    \ picking in all cases.\n"
  synonyms:
  - --disable_isotopic_transfer
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ''
  synonyms:
  - --in
  args: !RepeatFlagArg
    name: INFILES
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: "show this help message and exit\n--in INFILES [INFILES ...]\nA list\
    \ of transformation files in the same folder as\nthe .chrom.mzML files\n--peakgroups_infile\
    \ PEAKGROUPS_INFILE\nInfile containing peakgroups (outfile from\nfeature_alignment.py)\n\
    --out OUTPUT          Output file with imputed values\n--file_format FILE_FORMAT\n\
    Which input file format is used (openswath, mprophet\nor peakview)\n--out_matrix\
    \ MATRIX_OUTFILE\nMatrix containing one peak group per row (supports\n.csv, .tsv\
    \ or .xls)\n--matrix_output_method MATRIX_OUTPUT_METHOD\nWhich columns are written\
    \ besides Intensity (none, RT,\nscore, source or full)\n--border_option median\n\
    How to determine integration border (possible values:\nmax_width, mean, median).\
    \ Max width will use the\nmaximal possible width (most conservative since it\n\
    will overestimate the background signal).\n--dry_run             Perform a dry\
    \ run only\n--test                For running the tests (does not add a random\
    \ id to the\nresults)\n--cache_in_memory     Cache data from a single run in memory\n\
    --method METHOD       Which method to use (singleShortestPath,\nsingleClosestRun,\
    \ reference)\n--realign_runs REALIGN_METHOD\nHow to re-align runs in retention\
    \ time ('diRT': use\nonly deltaiRT from the input file, 'linear': perform a\n\
    linear regression using best peakgroups, 'splineR':\nperform a spline fit using\
    \ R, 'splineR_external':\nperform a spline fit using R (start an R process using\n\
    the command line), 'splinePy' use Python native spline\nfrom scikits.datasmooth\
    \ (slow!), 'lowess': use Robust\nlocally weighted regression (lowess smoother),\n\
    'nonCVSpline, CVSpline': splines with and without\ncross-validation, 'Earth' :\
    \ use Multivariate Adaptive\nRegression Splines using py-earth\n--verbosity VERBOSITY\n\
    Verbosity\n--do_single_run       Only do a single run"
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "WARNING: cannot import optimized MST alignment, will use Python version\
  \ (slower).\nusage: requantAlignedValues.py [-h] [--in INFILES [INFILES ...]]\n\
  \                               --peakgroups_infile PEAKGROUPS_INFILE --out\n  \
  \                             OUTPUT [--file_format FILE_FORMAT]\n             \
  \                  [--out_matrix MATRIX_OUTFILE]\n                             \
  \  [--matrix_output_method MATRIX_OUTPUT_METHOD]\n                             \
  \  [--border_option median] [--dry_run] [--test]\n                             \
  \  [--cache_in_memory] [--method METHOD]\n                               [--realign_runs\
  \ REALIGN_METHOD]\n                               [--verbosity VERBOSITY] [--do_single_run]\n\
  \                               [--disable_isotopic_grouping]\n                \
  \               [--disable_isotopic_transfer]\n\nThis program will impute missing\
  \ values\n\noptional arguments:\n  -h, --help            show this help message\
  \ and exit\n  --in INFILES [INFILES ...]\n                        A list of transformation\
  \ files in the same folder as\n                        the .chrom.mzML files\n \
  \ --peakgroups_infile PEAKGROUPS_INFILE\n                        Infile containing\
  \ peakgroups (outfile from\n                        feature_alignment.py)\n  --out\
  \ OUTPUT          Output file with imputed values\n  --file_format FILE_FORMAT\n\
  \                        Which input file format is used (openswath, mprophet\n\
  \                        or peakview)\n  --out_matrix MATRIX_OUTFILE\n         \
  \               Matrix containing one peak group per row (supports\n           \
  \             .csv, .tsv or .xls)\n  --matrix_output_method MATRIX_OUTPUT_METHOD\n\
  \                        Which columns are written besides Intensity (none, RT,\n\
  \                        score, source or full)\n  --border_option median\n    \
  \                    How to determine integration border (possible values:\n   \
  \                     max_width, mean, median). Max width will use the\n       \
  \                 maximal possible width (most conservative since it\n         \
  \               will overestimate the background signal).\n  --dry_run         \
  \    Perform a dry run only\n  --test                For running the tests (does\
  \ not add a random id to the\n                        results)\n  --cache_in_memory\
  \     Cache data from a single run in memory\n  --method METHOD       Which method\
  \ to use (singleShortestPath,\n                        singleClosestRun, reference)\n\
  \  --realign_runs REALIGN_METHOD\n                        How to re-align runs in\
  \ retention time ('diRT': use\n                        only deltaiRT from the input\
  \ file, 'linear': perform a\n                        linear regression using best\
  \ peakgroups, 'splineR':\n                        perform a spline fit using R,\
  \ 'splineR_external':\n                        perform a spline fit using R (start\
  \ an R process using\n                        the command line), 'splinePy' use\
  \ Python native spline\n                        from scikits.datasmooth (slow!),\
  \ 'lowess': use Robust\n                        locally weighted regression (lowess\
  \ smoother),\n                        'nonCVSpline, CVSpline': splines with and\
  \ without\n                        cross-validation, 'Earth' : use Multivariate\
  \ Adaptive\n                        Regression Splines using py-earth\n  --verbosity\
  \ VERBOSITY\n                        Verbosity\n  --do_single_run       Only do\
  \ a single run\n\nexperimental options:\n  --disable_isotopic_grouping\n       \
  \                 Disable grouping of isotopic variants by\n                   \
  \     peptide_group_label, thus disabling matching of\n                        isotopic\
  \ variants of the same peptide across channels.\n                        If turned\
  \ off, each isotopic channel will be matched\n                        independently\
  \ of the other. If enabled, the more\n                        certain identification\
  \ will be used to infer the\n                        location of the peak in the\
  \ other channel.\n  --disable_isotopic_transfer\n                        Disable\
  \ the transfer of isotopic boundaries in all\n                        cases. If\
  \ enabled (default), the best (best score)\n                        isotopic channel\
  \ dictates the peak boundaries and all\n                        other channels use\
  \ those boundaries. This ensures\n                        consistency in peak picking\
  \ in all cases.\n"
generated_using:
- --help
