!Command
command:
- jemalloc-config
positional: []
named:
- !Flag
  description: ': Print shared library revision number.'
  synonyms:
  - --revision
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print configure options used to build jemalloc.'
  synonyms:
  - --config
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print installation directory prefix.'
  synonyms:
  - --prefix
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print binary installation directory.'
  synonyms:
  - --bindir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print data installation directory.'
  synonyms:
  - --datadir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print include installation directory.'
  synonyms:
  - --includedir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print library installation directory.'
  synonyms:
  - --libdir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print manual page installation directory.'
  synonyms:
  - --mandir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print compiler used to build jemalloc.'
  synonyms:
  - --cc
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print compiler flags used to build jemalloc.'
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print preprocessor flags used to build jemalloc.'
  synonyms:
  - --cppflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print library flags used to build jemalloc.'
  synonyms:
  - --ldflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: ': Print libraries jemalloc was linked against.'
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: '| -h  : Print usage.'
  synonyms:
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag: !Flag
  description: ': Print jemalloc version.'
  synonyms:
  - --version
  args: !EmptyFlagArg {}
  optional: true
help_text: "Usage:\n  /usr/local/bin/jemalloc-config <option>\nOptions:\n  --help\
  \ | -h  : Print usage.\n  --version    : Print jemalloc version.\n  --revision \
  \  : Print shared library revision number.\n  --config     : Print configure options\
  \ used to build jemalloc.\n  --prefix     : Print installation directory prefix.\n\
  \  --bindir     : Print binary installation directory.\n  --datadir    : Print data\
  \ installation directory.\n  --includedir : Print include installation directory.\n\
  \  --libdir     : Print library installation directory.\n  --mandir     : Print\
  \ manual page installation directory.\n  --cc         : Print compiler used to build\
  \ jemalloc.\n  --cflags     : Print compiler flags used to build jemalloc.\n  --cppflags\
  \   : Print preprocessor flags used to build jemalloc.\n  --ldflags    : Print library\
  \ flags used to build jemalloc.\n  --libs       : Print libraries jemalloc was linked\
  \ against.\n"
generated_using:
- --help
