!Command
command:
- ansible-galaxy
positional:
- !Positional
  description: ''
  position: 0
  name: init|info|install|list|remove
  optional: true
named: []
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "Usage: ansible-galaxy [init|info|install|list|remove] [--help] [options]\
  \ ...\n\nOptions:\n  -h, --help  show this help message and exit\n\nSee 'ansible-galaxy\
  \ <command> --help' for more information on a specific command.\n\n"
generated_using:
- --help
