!Command
command:
- mysql_config
positional: []
named:
- !Flag
  description: '[-I/usr/local/include]'
  synonyms:
  - --cflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[-I/usr/local/include]'
  synonyms:
  - --cxxflags
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[-I/usr/local/include]'
  synonyms:
  - --include
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[-L/usr/local/lib -lmysqlclient -lpthread -lm -lrt -ldl]'
  synonyms:
  - --libs
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[-L/usr/local/lib -lmysqlclient -lpthread -lm -lrt -ldl]'
  synonyms:
  - --libs_r
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[/usr/local/lib/plugin]'
  synonyms:
  - --plugindir
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: '[/tmp/mysql.sock]'
  synonyms:
  - --socket
  args: !EmptyFlagArg {}
  optional: true
- !Flag
  description: "VAR is one of:\npkgincludedir [/usr/local/include]\npkglibdir    \
    \ [/usr/local/lib]\nplugindir     [/usr/local/lib/plugin]\n"
  synonyms:
  - --variable
  args: !SimpleFlagArg
    name: VAR
  optional: true
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Usage: /usr/local/bin/mysql_config [OPTIONS]\nOptions:\n        --cflags\
  \         [-I/usr/local/include]\n        --cxxflags       [-I/usr/local/include]\n\
  \        --include        [-I/usr/local/include]\n        --libs           [-L/usr/local/lib\
  \ -lmysqlclient -lpthread -lm -lrt -ldl]\n        --libs_r         [-L/usr/local/lib\
  \ -lmysqlclient -lpthread -lm -lrt -ldl]\n        --plugindir      [/usr/local/lib/plugin]\n\
  \        --socket         [/tmp/mysql.sock]\n        --port           [0]\n    \
  \    --version        [6.1.6]\n        --variable=VAR   VAR is one of:\n       \
  \         pkgincludedir [/usr/local/include]\n                pkglibdir     [/usr/local/lib]\n\
  \                plugindir     [/usr/local/lib/plugin]\n"
generated_using:
- --help
