!Command
command:
- phyluce_probe_remove_overlapping_probes_given_config
positional: []
named:
- !Flag
  description: The input probe file
  synonyms:
  - --probes
  args: !SimpleFlagArg
    name: PROBES
  optional: true
- !Flag
  description: The input conf file of probes names to remove
  synonyms:
  - --config
  args: !SimpleFlagArg
    name: CONFIG
  optional: true
- !Flag
  description: The output probe file to write
  synonyms:
  - --output
  args: !SimpleFlagArg
    name: OUTPUT
  optional: true
parent:
subcommands: []
usage: []
help_flag: !Flag
  description: show this help message and exit
  synonyms:
  - -h
  - --help
  args: !EmptyFlagArg {}
  optional: true
usage_flag:
version_flag:
help_text: "usage: phyluce_probe_remove_overlapping_probes_given_config\n       [-h]\
  \ --probes PROBES --config CONFIG --output OUTPUT\n\nProgram description\n\noptional\
  \ arguments:\n  -h, --help       show this help message and exit\n  --probes PROBES\
  \  The input probe file\n  --config CONFIG  The input conf file of probes names\
  \ to remove\n  --output OUTPUT  The output probe file to write\n"
generated_using:
- --help
